# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

next = Suivant
unknown-os = OS inconnu
parttype-root = Racine du système de fichiers ({ $path })
parttype-esp = Partition système EFI ({ $path })
parttype-home = Données de l'utilisateur ({ $path })
parttype-var = Données variables ({ $path })
page-welcome = Bienvenue sur { $distro }
page-welcome-try = Essayer
page-welcome-install = Installer
page-failure = Échec de l'installation
page-failure-close = Fermer
page-failure-bug = Signaler un bogue
page-language = Langue
page-language-search-lang = Rechercher une langue/localisation…
page-language-next = Suivant
page-completed = Complète
page-completed-desc = L'installation est terminée. Vous pouvez maintenant redémarrer et profiter de votre nouveau système.
page-completed-close = Fermer
page-completed-reboot = Redémarrer
page-destination = Destination
page-destination-scanning = Recherche des disques
page-destination-wait = En attente de os-prober…
page-destination-no-disk = Aucun disque n'a été trouvé
page-installdual = Double démarrage
page-installdual-otheros = Autres OS
page-confirmation = Confirmation
page-installation = Installation
page-installation-welcome-desc = Apprenez à connaître votre nouveau système d'exploitation.
page-installation-help = Besoin d'aide ?
page-installation-help-desc = Posez votre question dans l'un de nos chats !
page-installation-contrib = Contribuer à { $distro }
page-installation-progress = Installation du système de base...
page-installcustom = Installation sur mesure
page-installcustom-title = Partitions et points de montage
page-installcustom-desc = { $num } définition(s)
page-installcustom-tool = Ouvrir l'outil de partitionnement
page-installationtype = Type d'installation
page-installationtype-entire = Disque Entier
page-installationtype-tpm = Activer le TPM
page-installationtype-chromebook = Chromebook
page-installationtype-custom = Sur mesure
dialog-installtype-encrypt = Chiffrement des disques
dialog-installtype-password = Mot de passe
dialog-installtype-repeat = Resaissisez le mot de passe
dialog-installtype-cancel = Annuler
dialog-installtype-confirm = Confirmer
installtype-edit-mp = Modifier un point de montage
installtype-rm-mp = Supprimer un point de montage
dialog-mp-part = Partition
dialog-mp-at = Monter sur
dialog-mp-opts = Options de montage
installtype-parttool = Sélectionnez votre outil de partitionnement
stage-extracting = Extraction des fichiers
stage-copying = Copie des fichiers
stage-initramfs = Régénération de initramfs
stage-grub1 = Génération du fichier grub.cfg de l'étape 1 dans ESP...
stage-biosgrub = Installation BIOS de Grub2
stage-kernel = Réinstallation des noyaux
prev = Précédent
parttype-extendedboot = Partition du chargeur de démarrage étendu ({ $path })
page-destination-no-disk-desc = Il n'y a pas de disques adaptés à l'installation.
stage-mkpart = Création des partitions et copie des fichiers
page-welcome-desc = Testez { $distro } à partir de ce programme d'installation ou lancez l'installation maintenant. Vous pouvez toujours revenir à cet écran en sélectionnant « Installer » dans le menu.
page-installation-contrib-desc = Découvrez comment apporter votre contribution en termes de temps, d'argent ou de matériel.
page-installcustom-add = Ajouter une nouvelle définition/rangée
parttype-other = Point de montage de partitionnement personnalisé
page-installationtype-encrypt = Activer le chiffrement des disques
page-installationtype-dual = Double Démarrage
stage-grub2 = Génération de l'étape 2 de grub.cfg dans /boot/grub2/grub.cfg....
dialog-installtype-encrypt-desc =
    Veuillez définir le mot de passe de chiffrement du disque.
    Si vous perdez le mot de passe, vos données ne seront pas récupérables.
stage-grub = Génération des valeurs systèmes par défaut pour grub
stage-selinux = Définition des étiquettes SELinux
