# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

prev = Föregående
next = Nästa
page-welcome-try = Prova
page-welcome-install = Installera
page-failure = Installationen misslyckades
page-failure-close = Stäng
page-failure-bug = Rapportera en bugg
page-language = Språk
page-language-next = Nästa
page-completed-close = Stäng
page-completed-reboot = Starta om
page-destination = Plats
page-confirmation = Bekräftelse
page-installation = Installation
page-installation-progress = Installerar bas-systemet...
page-installationtype = Typ av installation
page-installationtype-chromebook = Chromebook
unknown-os = Okänt OS
page-installationtype-custom = Anpassad
dialog-installtype-password = Lösenord
dialog-installtype-cancel = Avbryt
dialog-installtype-confirm = Bekräfta
dialog-mp-part = Partition
page-destination-scanning = Skannar diskar
page-installdual-otheros = Andra OS
page-installation-help = Behöver du hjälp?
page-installcustom = Anpassad installation
page-installationtype-entire = Hela disken
page-installationtype-tpm = Aktivera TPM
dialog-installtype-encrypt = Diskkryptering
dialog-installtype-repeat = Repetera lösenordet igen
installtype-edit-mp = Redigera monteringspunkt
installtype-rm-mp = Ta bort monteringspunkt
dialog-mp-opts = Alternativ för montering
stage-extracting = Extraherar filer
stage-copying = Kopierar filer
stage-initramfs = Genererar initramfs igen
stage-kernel = Installerar om kärnor
parttype-other = Anpassad monteringspunkt för partitioner
page-destination-wait = Väntar på os-prober…
page-destination-no-disk = Inga diskar hittades
page-installcustom-title = Partitioner och monteringspunkter
page-installcustom-tool = Öppna partitioneringsverktyget
page-installationtype-encrypt = Aktivera diskkryptering
stage-biosgrub = Installerar Grub2-BIOS:en
stage-selinux = Ställer in etiketter för SELinux
dialog-confirm-warn-efipartfound-title = EFI-partition upptäcktes
page-installcustom-add = Lägg till en ny definition/rad
installtype-parttool = Välj ditt partitioneringsverktyg
parttype-root = Root för filsystemet ({ $path })
parttype-home = Användardata ({ $path })
parttype-var = Varabeldata ({ $path })
page-welcome = Välkommen till { $distro }
page-installation-contrib = Bidra till { $distro }
stage-mkpart = Skapar partitioner och kopierar filer
