//! The Readymade playbook type describes the operation for Readymade to perform.
//! It is designed to be serializable and deserializable, so that it can be easily stored and transmitted,
//! but should be generated by an external program such as a GUI app or template system, rather than being manually written by users,
//! since it is relatively low-level and specific to a particular install (ex. hardcoded disk paths).

use serde::{Deserialize, Serialize};
use std::path::PathBuf;

/// The encryption configuration for the installation, used by provisioners to determine how to set up encryption on the installation.
#[derive(Default, Serialize, Deserialize, Clone, educe::Educe)]
#[educe(Debug)]
pub struct EncryptionConfig {
    /// Whether to use TPM for encryption.
    pub tpm: bool,
    /// The encryption key to use for installation.
    #[educe(Debug(ignore))]
    pub encryption_key: String,
}

/// The main playbook type, which describes the installation operation to be performed by Readymade.
#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct Playbook {
    /// The disk to install to, this should be a whole disk (ex. /dev/sda) rather than a partition (ex. /dev/sda1).
    pub destination_disk: PathBuf,
    /// The encryption configuration for the installation.
    pub encryption: Option<EncryptionConfig>,
    /// The disk provisioner to use for the installation, which describes how the installation disk should be partitioned and setup. Some disk provisioners support copying files to the installation disk, making a filesystem provisioner optional.
    pub disk_provisioner: Option<crate::backend::provisioners::DiskProvisioner>,
    /// The filesystem provisioner to use for the installation, which describes how the installation files should be copied to the partitions after they are set up by the disk provisioner.
    pub filesystem_provisioner: Option<crate::backend::provisioners::FilesystemProvisioner>,
    /// The post-installation modules to run after the provisioning step is complete, used to perform additional configuration on the installation such as installing a bootloader, configuring SELinux, or running custom scripts.
    pub postinstall: Vec<crate::backend::postinstall::Module>,
}
