[install]
allowed_installtypes = ["wholedisk"]

[distro]
name = "Ultramarine Linux"

[[postinstall]]
module = "CleanupBoot"

[[postinstall]]
module = "ReinstallKernel"

[[postinstall]]
module = "Dracut"

[[postinstall]]
module = "GRUB2"

[[postinstall]]
module = "PrepareFedora"

[[postinstall]]
module = "SELinux"

[[postinstall]]
module = "EfiStub"

[[postinstall]]
module = "InitialSetup"

[[postinstall]]
module = "Language"

[[postinstall]]
module = "Script"
