[install]
allowed_installtypes = ["wholedisk", "dualboot", "custom"]

[distro]
name = "Ultramarine Linux"

[[postinstall]]
module = "GRUB2"

[[postinstall]]
module = "CleanupBoot"

[[postinstall]]
module = "ReinstallKernel"

[[postinstall]]
module = "Dracut"

[[postinstall]]
module = "PrepareFedora"

[[postinstall]]
module = "SELinux"

[[postinstall]]
module = "Drivers"
