[install]
allowed_installtypes = ["wholedisk"]

[distro]
name = "Ultramarine Linux"

[[bento]]
title = "page-welcome"
desc = "page-installation-welcome-desc"
link = "https://wiki.ultramarine-linux.org/en/welcome/"
icon = "explore-symbolic"

[[bento]]
title = "page-installation-help"
desc = "page-installation-help-desc"
link = "https://wiki.ultramarine-linux.org/en/community/community/"
icon = "chat-symbolic"

[[bento]]
title = "page-installation-contrib"
desc = "page-installation-contrib-desc"
link = "https://wiki.ultramarine-linux.org/en/contributing/contributorguide/"
icon = "applications-development-symbolic"

[[postinstall]]
module = "CleanupBoot"

[[postinstall]]
module = "ReinstallKernel"

[[postinstall]]
module = "Dracut"

[[postinstall]]
module = "GRUB2"

[[postinstall]]
module = "PrepareFedora"

[[postinstall]]
module = "SELinux"

[[postinstall]]
module = "EfiStub"

[[postinstall]]
module = "InitialSetup"

[[postinstall]]
module = "Language"

[[postinstall]]
module = "Script"
