use std::io::Write;

use super::{Context, PostInstallModule};
use color_eyre::Result;
use serde::{Deserialize, Serialize};

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq)]
pub struct CryptSetup;

impl PostInstallModule for CryptSetup {
    fn run(&self, context: &Context) -> Result<()> {
        let mut f = std::fs::File::create("/etc/crypttab")?;

        f.write_all(b"# This file is generated by Readymade.\n")?;
        // need to get partition list???

        Ok(())
    }
}
