on: push

name: Build RPM snapshot package


jobs:
  format:
    runs-on: ubuntu-latest
    container:
        image: ghcr.io/terrapkg/builder:f40
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: dnf builddep -y ci/readymade.spec

      - name: run rpmbuild
        run: |
            git_sha=${{ github.sha }}
            git_short=${git_sha:0:7}
            rpmdev-setuptree
            rpmbuild -ba ci/readymade.spec --define "gitcommit $git_sha" --define "shortcommit $git_short" --define "_rpmdir $PWD" --define "_disable_source_fetch 0"

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          path: "*.rpm"
