name: Rust

on:
  push:
  pull_request:

jobs:
  rust:
    uses: FyraLabs/actions/.github/workflows/rust.yml@main
    with:
      test-container: '{"image": "ghcr.io/tau-os/builder:main"}'
      test-pre: dnf builddep -y 'pkgconfig(libhelium-1)' 'pkgconfig(gnome-desktop-4)' clang-devel gcc mold